### PR TITLE
fix: invalid string characters

### LINKED ISSUE #4: Error decoding Logic Pro preferences
I get this error trying to open the plist file (attached). 

> Failed to decode binary plist 'com.apple.logic10.plist'. RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 16

[com.apple.logic10.plist.zip](https://github.com/ivanhernandez13/vscode-plist/files/14472160/com.apple.logic10.plist.zip)

### PR DESCRIPTION
**Pull request by dnicolson**
Fixes https://github.com/ivanhernandez13/vscode-plist/issues/4.

### CODE REVIEW

File: src/core/binary/node/decoder.ts [hunk 1]
```diff
@@ -4,6 +4,8 @@ import * as plist from 'plist';
 import {decodeBinaryPlist} from '../decoder/binary_plist_decoder';
 import {plutil} from '../../../common/utilities/node/plutil';
 import {BinaryPlistDocument} from '../binary_plist_document';
+// eslint-disable-next-line node/no-extraneous-import
+import {CreateOptions} from 'xmlbuilder';
```
Comment (cunneen) [inline src/core/binary/node/decoder.ts:8]: Does it work if this is changed to add the `type` keyword? i.e.:

```ts
import {type CreateOptions} from 'xmlbuilder';
```

If so then you'll be able to remove the `// @ts-ignore` and `// eslint-disable...` comments

File: src/core/binary/node/decoder.ts [hunk 2]
```diff
@@ -4,6 +4,8 @@ import * as plist from 'plist';
 import {decodeBinaryPlist} from '../decoder/binary_plist_decoder';
 import {plutil} from '../../../common/utilities/node/plutil';
 import {BinaryPlistDocument} from '../binary_plist_document';
+// eslint-disable-next-line node/no-extraneous-import
```
Comment (cunneen) [inline src/core/binary/node/decoder.ts:7]: remove? See comment below.

File: src/core/binary/node/decoder.ts [hunk 3]
```diff
@@ -21,7 +23,16 @@ export async function generateTextualPlist(
     );
   } else {
     const content = await decodeBinaryPlist(document.uri);
-    const plistContent = plist.build(content as plist.PlistValue);
+    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
+    // @ts-ignore
```
Comment (cunneen) [inline src/core/binary/node/decoder.ts:27]: remove? See comment above.

File: package.json [hunk 4]
```diff
@@ -179,7 +179,7 @@
   },
   "dependencies": {
     "@vscode/codicons": "^0.0.32",
-    "plist": "^3.1.0"
+    "plist": "github:TooTallNate/plist.js#pull/144/head"
```
Comment (cunneen) [inline package.json:182]: Your PR to the `plist.js` repo looks good to me. It makes sense to enable an `invalidCharReplacement` to be passed through to `xmlbuilder`.
I'm a little wary of having a dependency on a PR branch, as I'm not sure what happens when the PR branch is deleted (which is quite normal after a merge), even though that repo seems dead.

Do you think we can use [@expo/plist](https://www.npmjs.com/package/@expo/plist) instead? It looks better-maintained.

File: src/core/binary/node/decoder.ts [hunk 5]
```diff
@@ -21,7 +23,16 @@ export async function generateTextualPlist(
...
+    const plistContent = plist.build(content as plist.PlistValue, {}, {
+      invalidCharReplacement: '�',
+    } as CreateOptions);
+    if (plistContent.indexOf('�') !== -1) {
+      vscode.window.showWarningMessage(
+        'This file contains “�” characters, likely due to control characters in strings. If you save the file, these replacement characters will remain.'
```
Comment (cunneen) [inline src/core/binary/node/decoder.ts]: I like this solution, but I think the warning message could be confusing. A user receiving this message is likely to through their file to try and find the `�` character that "this file contains", only to determine that the warning message is wrong.

**Review by cunneen — CHANGES_REQUESTED** [review]
Thanks for this! I'd like to merge it, but please see my comments below and let me know what you think.

File: src/core/binary/node/decoder.ts (hunk 1 above)
Comment (dnicolson) [reply src/core/binary/node/decoder.ts:8]: It's still needed. The method signature needs to be updated [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/plist/index.d.ts#L10), then it can be removed.

File: package.json (hunk 4 above)
Comment (dnicolson) [reply package.json:182]: I think it's okay to use the PR as a dependency. I tested it with a closed PR, and it still resolves correctly. The diffs continue to work as well.

I wasn't able to install the dependencies with [@expo/plist](https://www.npmjs.com/package/@expo/plist), it is also missing the latest merges in the original project.

File: src/core/binary/node/decoder.ts (hunk 5 above)
Comment (dnicolson) [reply src/core/binary/node/decoder.ts]: I made some changes, please let me know if you have any suggestions.

Comment (cunneen) [reply src/core/binary/node/decoder.ts]: Perfect. You've worded that better than I could have. Thanks!
